unstable_features = true

edition = "2021"

comment_width = 80
wrap_comments = true

# fn_args_layout = "Compressed"
fn_single_line = true

# force_multiline_blocks = true

format_code_in_doc_comments = true

format_strings = true

# imports_indent = "Visual"
# indent_style = "Visual"

match_block_trailing_comma = true

max_width = 80

reorder_impl_items = true

group_imports = "StdExternalCrate"

struct_lit_width = 80

tab_spaces = 2
